
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Tue Apr 09 17:24:20 BST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int TIMES = 14;
  static final int LT = 17;
  static final int ELSE = 8;
  static final int PLUS = 5;
  static final int INT = 29;
  static final int RPAREN = 22;
  static final int EQUAL = 20;
  static final int LTE = 19;
  static final int ENDIF = 9;
  static final int THEN = 7;
  static final int CALL = 12;
  static final int SEMI = 4;
  static final int WHILE = 3;
  static final int END = 11;
  static final int FUNCTION = 10;
  static final int IF = 6;
  static final int LPAREN = 21;
  static final int GT = 16;
  static final int ID = 28;
  static final int GTE = 18;
  static final int DO = 2;
  static final int ASSIGNS = 23;
  static final int COMMA = 25;
  static final int EOF = 0;
  static final int DIVIDE = 15;
  static final int FINISH = 27;
  static final int MINUS = 13;
  static final int PRINT = 24;
  static final int error = 1;
  static final int START = 26;
}

